#!/bin/bash

# shnake - classic snake game in bash.
#
# Copyright (c) 2011 Cesar L. B. Silveira
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Move command codes
up=1
down=2
right=3
left=4

# Game area limits
min_x=4
max_x=76
min_y=4
max_y=20

# State data
running=1
direction=$right
size=5

# The snake itself, and the food "object"
declare -a snake_x
declare -a snake_y
declare -a food

function graphicsmode {
    echo -e '\033(0'
}

function textmode {
    echo -e '\033(1'
}

function saveterm {
    term_settings=$(stty -g)
}

function restoreterm {
    stty $term_settings
}

# Echo data on given screen coordinates
function echoxy {
    echo -e '\033['$2';'$1'H'$3
}

# Draw the game area border
function drawborder {
    x0=$1
    y0=$2
    x1=$3
    y1=$4

    graphicsmode

    echoxy $x0 $y0 l
    echoxy $x0 $y1 m
    echoxy $x1 $y0 k
    echoxy $x1 $y1 j

    for ((x=$x0+1; x<$x1; x++)); do
        echoxy $x $y0 q
        echoxy $x $y1 q
    done

    for ((y=$y0+1; y<$y1; y++)); do
        echoxy $x0 $y x
        echoxy $x1 $y x
    done

    textmode
}

# Move the snake one tile on the game area
function move {
    echoxy ${snake_x[$(($size - 1))]} ${snake_y[$(($size - 1))]} '\040'

    for((i=$size-1; i>0; i--)); do
        snake_x[$i]=${snake_x[$i-1]}
        snake_y[$i]=${snake_y[$i-1]}
    done

    case $direction in
        $up)
            snake_y[0]=$((${snake_y[0]} - 1)) ;;
        $right)
            snake_x[0]=$((${snake_x[0]} + 1)) ;;
        $down)
            snake_y[0]=$((${snake_y[0]} + 1)) ;;
        $left)
            snake_x[0]=$((${snake_x[0]} - 1)) ;;
    esac

    graphicsmode

    echoxy ${snake_x[0]} ${snake_y[0]} a

    textmode
}

# Place the food at some random position on the game area
function putfood {
    food[0]=$(($min_x + ($RANDOM % ($max_x - $min_x))))
    food[1]=$(($min_y + ($RANDOM % ($max_y - $min_y))))

    echoxy ${food[0]} ${food[1]} '*'
}

# Initialize the snake
function initsnake {
    for((i=$size-1,k=0; i>=0; i--,k++)); do
        snake_x[$i]=$(($min_x + 4 + $k))
        snake_y[$i]=$(($min_y + (($max_y - $min_y) / 2)))
    done
}

# Draw the snake
function putsnake {
    graphicsmode

    for((i=0; i<$size; i++)); do
        echoxy ${snake_x[$i]} ${snake_y[$i]} a
    done

    textmode
}

# Increment snake size by 1
function growsnake {
    for((i=$size; i>0; i--)); do
        snake_x[$i]=${snake_x[$(($i - 1))]}
        snake_y[$i]=${snake_y[$(($i - 1))]}
    done

    size=$(($size + 1))

    snake_x[0]=${food[0]}
    snake_y[0]=${food[1]}

    graphicsmode
    echoxy ${snake_x[0]} ${snake_y[0]} a
    textmode

    putfood
}

# "Main"
clear
drawborder $min_x $min_y $max_x $max_y

# Store terminal settings
saveterm

# This is what allows the script to detect keystrokes
# without requiring the user to press the Enter key
stty -icanon min 0 time 0 -echo

# Initialize
initsnake
putsnake
putfood

# Game loop
while(($running)); do
    read key

    case $key in
        w)
            if ((direction == left || direction == right)); then
                direction=$up
            fi
            ;;
        a)
            if ((direction == up || direction == down)); then
                direction=$left
            fi
            ;;
        s)
            if ((direction == left || direction == right)); then
                direction=$down
            fi
            ;;
        d)
            if ((direction == up || direction == down)); then
                direction=$right
            fi
            ;;
        q) running=0 ;;
    esac

    move

    case $direction in
        $up)
            if((${snake_x[0]} == ${food[0]} &&
                ${snake_y[0]} - 1 == ${food[1]})); then
                growsnake
            fi
        ;;
        $right)
            if((${snake_x[0]} + 1 == ${food[0]} &&
                ${snake_y[0]} == ${food[1]})); then
                growsnake
            fi
        ;;
        $down)
            if((${snake_x[0]} == ${food[0]} &&
                ${snake_y[0]} + 1 == ${food[1]})); then
                growsnake
            fi
        ;;
        $left)
            if((${snake_x[0]} - 1 == ${food[0]} &&
                ${snake_y[0]} == ${food[1]})); then
                growsnake
            fi
        ;;
    esac

    sleep 0.1
done

# Restore terminal settings
restoreterm
